trigger: none

pool:
  name: Default 

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform Tool Install'
  
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: 'Terraform init'

  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
    backendServiceArm: 'Noise_control_project_service_connection'
    backendAzureRmResourceGroupName: 'Abhishek_RG_donot_delete'
    backendAzureRmStorageAccountName: 'tfstorageabhi2424'
    backendAzureRmContainerName: 'homelockcontainer'
    backendAzureRmKey: 'dev_noise_tfstate'

- task: TerraformTaskV4@4
  displayName: 'Terraform plan'

  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
    environmentServiceNameAzureRM: 'Noise_control_project_service_connection'

- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
    environmentServiceNameAzureRM: 'Noise_control_project_service_connection'