
trigger: none

pool: Default

steps:

# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.11.0'
#     addToPath: false
#     architecture: 'x64'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -UseBasicParsing -Uri 'https://www.python.org/ftp/python/3.11.0/python-3.11.0-amd64.exe' -OutFile 'c:/temp/python-3.11.0-amd64.exe'
      
      c:/temp/python-3.11.0-amd64.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
      
      python --version
      pip install --user yamllint
      yamllint --version